apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
    name: marketplace-grafana
    labels:
        app.kubernetes.io/name: marketplace-grafana
spec:
    version: "11.3.0"
    config:
        auth:
            disable_login_form: "false"
            disable_signout_menu: "false"
        security:
            admin_user: admin
            admin_password: grafana
    resources:
        requests:
            memory: 128Mi
            cpu: 100m
        limits:
            memory: 256Mi
            cpu: 200m
    dashboards:
        configMaps:
            - name: marketplace-grafana-dashboards
