apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketplace-bot-prod

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - bot.yaml

labels:
  - pairs:
      app: marketplace-price-tracker
      managed-by: kustomize

commonAnnotations:
  description: "Marketplace Price Tracker Bot - Telegram bot for tracking marketplace prices"
images:
  - name: ghcr.io/vshulcz/marketplace_price_tracker
    newTag: latest
